import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assetRoot = resolve(projectRoot, 'img');
const reportPath = resolve(projectRoot, 'docs', 'ASSET_AUDIT.md');
const ignoredDirectories = new Set(['.git', 'dist', 'media-review', 'node_modules']);
const readableExtensions = new Set(['.css', '.html', '.js', '.json', '.md', '.txt']);
const largeAssetThreshold = 2 * 1024 * 1024;

const collectFiles = (directory) => readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
  if (ignoredDirectories.has(entry.name)) return [];

  const entryPath = resolve(directory, entry.name);
  return entry.isDirectory() ? collectFiles(entryPath) : [entryPath];
});

const formatBytes = (bytes) => {
  const megabytes = bytes / (1024 * 1024);
  return megabytes >= 0.1 ? `${megabytes.toFixed(2)} MB` : `${(bytes / 1024).toFixed(1)} KB`;
};

const normalizePath = (filePath) => relative(projectRoot, filePath).replaceAll('\\', '/');
const sourceFiles = collectFiles(projectRoot).filter((filePath) => (
  filePath !== reportPath && readableExtensions.has(extname(filePath).toLowerCase())
));
const sourceText = sourceFiles
  .map((filePath) => readFileSync(filePath, 'utf8'))
  .join('\n')
  .replaceAll('\\', '/');
const assetFiles = collectFiles(assetRoot);

const assets = assetFiles.map((filePath) => {
  const path = normalizePath(filePath);
  const encodedPath = path.split('/').map(encodeURIComponent).join('/');
  const basename = path.slice(path.lastIndexOf('/') + 1);
  const isReferenced = sourceText.includes(path)
    || sourceText.includes(`/${path}`)
    || sourceText.includes(encodedPath)
    || sourceText.includes(encodeURIComponent(basename));

  return {
    filePath,
    path,
    size: statSync(filePath).size,
    isReferenced
  };
});

const duplicateGroups = new Map();
assets.forEach((asset) => {
  const hash = createHash('sha256').update(readFileSync(asset.filePath)).digest('hex');
  const group = duplicateGroups.get(hash) ?? [];
  group.push(asset);
  duplicateGroups.set(hash, group);
});

const duplicates = [...duplicateGroups.values()]
  .filter((group) => group.length > 1)
  .sort((first, second) => second[0].size - first[0].size);
const largeAssets = assets
  .filter((asset) => asset.size >= largeAssetThreshold)
  .sort((first, second) => second.size - first.size);
const possiblyUnused = assets
  .filter((asset) => !asset.isReferenced)
  .sort((first, second) => second.size - first.size);
const totalSize = assets.reduce((sum, asset) => sum + asset.size, 0);
const possibleSavings = possiblyUnused.reduce((sum, asset) => sum + asset.size, 0);

const lines = [
  '# Asset Audit',
  '',
  '> Generated by `npm run assets:audit`. References are detected heuristically; review files before deleting them.',
  '',
  '## Summary',
  '',
  `- Image directory: ${assets.length} files (${formatBytes(totalSize)})`,
  `- Large assets (2 MB or more): ${largeAssets.length}`,
  `- Exact duplicate groups: ${duplicates.length}`,
  `- Possibly unreferenced: ${possiblyUnused.length} files (${formatBytes(possibleSavings)})`,
  '',
  '## Large Assets',
  '',
  '| File | Size |',
  '| --- | ---: |',
  ...largeAssets.map((asset) => `| \`${asset.path}\` | ${formatBytes(asset.size)} |`),
  '',
  '## Exact Duplicates',
  ''
];

if (duplicates.length) {
  duplicates.forEach((group, index) => {
    lines.push(`### Group ${index + 1} (${formatBytes(group[0].size)} each)`, '');
    group.forEach((asset) => lines.push(`- \`${asset.path}\``));
    lines.push('');
  });
} else {
  lines.push('No exact duplicates found.', '');
}

lines.push('## Possibly Unreferenced', '');
if (possiblyUnused.length) {
  lines.push('| File | Size |', '| --- | ---: |');
  possiblyUnused.forEach((asset) => lines.push(`| \`${asset.path}\` | ${formatBytes(asset.size)} |`));
} else {
  lines.push('No unreferenced assets detected.');
}
lines.push('');

writeFileSync(reportPath, `${lines.join('\n')}\n`, 'utf8');
console.log(`Audited ${assets.length} image assets. Report: ${normalizePath(reportPath)}`);
